<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9794f278860f7fd30af2306bc45f5ead
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9794f278860f7fd30af2306bc45f5ead::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9794f278860f7fd30af2306bc45f5ead::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
